// Package templates renders HtmlGraph work items to HTML using Mustache
// templates. The templates are embedded at compile time and produce output
// compatible with the Python to_html() methods, ensuring both runtimes can
// read and write the same .htmlgraph/ HTML files.
//
// Templates use a subset of the Mustache spec (variables, sections, inverted
// sections) implemented in mustache.go with zero external dependencies. The
// same .mustache files work with Python's chevron library.
package templates

import (
	"embed"
	"fmt"
	"strings"

	"github.com/shakestzd/htmlgraph/internal/models"
)

//go:embed *.mustache
var templateFS embed.FS

// RenderNode renders any Node to HTML by dispatching on node.Type.
func RenderNode(node *models.Node) (string, error) {
	switch node.Type {
	case "feature":
		return RenderFeature(node)
	case "bug":
		return RenderBug(node)
	case "spike":
		return RenderSpike(node, "", "", 0)
	case "track":
		return RenderTrack(node)
	default:
		return RenderFeature(node) // fallback to generic node template
	}
}

// RenderFeature renders a feature node to HTML.
func RenderFeature(node *models.Node) (string, error) {
	data := prepareNodeData(node)
	return renderTemplate("feature.mustache", data)
}

// RenderBug renders a bug node to HTML.
func RenderBug(node *models.Node) (string, error) {
	data := prepareNodeData(node)
	return renderTemplate("bug.mustache", data)
}

// RenderSpike renders a spike node to HTML, including spike-specific fields.
func RenderSpike(node *models.Node, findings, decision string, timeboxHours int) (string, error) {
	data := prepareNodeData(node)
	data["spike_type"] = spikeTypeOrDefault(node)
	data["spike_type_display"] = titleCase(spikeTypeOrDefault(node))
	if timeboxHours > 0 {
		data["timebox_hours"] = timeboxHours
	}
	if findings != "" {
		data["has_findings"] = true
		data["findings"] = findings
	}
	if decision != "" {
		data["has_decision"] = true
		data["decision"] = decision
	}
	return renderTemplate("spike.mustache", data)
}

// RenderTrack renders a track node to HTML.
func RenderTrack(node *models.Node) (string, error) {
	data := prepareNodeData(node)
	return renderTemplate("track.mustache", data)
}

// RenderSession renders a session to HTML.
func RenderSession(sess *models.Session) (string, error) {
	data := prepareSessionData(sess)
	return renderTemplate("session.mustache", data)
}

// renderTemplate loads a template from the embedded FS and renders it.
func renderTemplate(name string, data map[string]any) (string, error) {
	tmplBytes, err := templateFS.ReadFile(name)
	if err != nil {
		return "", fmt.Errorf("load template %s: %w", name, err)
	}
	result, err := mustacheRender(string(tmplBytes), data)
	if err != nil {
		return "", fmt.Errorf("render template %s: %w", name, err)
	}
	return result, nil
}

// prepareNodeData converts a Node into a map suitable for Mustache rendering.
func prepareNodeData(node *models.Node) map[string]any {
	data := map[string]any{
		"id":               node.ID,
		"title":            node.Title,
		"type":             node.Type,
		"status":           string(node.Status),
		"priority":         string(node.Priority),
		"status_display":   statusDisplay(string(node.Status)),
		"priority_display": titleCase(string(node.Priority)),
		"created_at":       formatTime(node.CreatedAt),
		"updated_at":       formatTime(node.UpdatedAt),
		"stylesheet_path":  "../styles.css",
	}

	if node.AgentAssigned != "" {
		data["agent_assigned"] = node.AgentAssigned
	}
	if node.TrackID != "" {
		data["track_id"] = node.TrackID
	}
	if node.SpikeSubtype != "" {
		data["spike_subtype"] = node.SpikeSubtype
	}
	if node.AutoGenerated {
		data["auto_generated"] = "true"
	}
	if node.SessionID != "" {
		data["session_id"] = node.SessionID
	}
	if node.FromFeatureID != "" {
		data["from_feature_id"] = node.FromFeatureID
	}
	if node.ToFeatureID != "" {
		data["to_feature_id"] = node.ToFeatureID
	}
	if node.ModelName != "" {
		data["model_name"] = node.ModelName
	}
	if node.ContextTokensUsed > 0 {
		data["context_tokens"] = node.ContextTokensUsed
	}
	if node.ContextPeakTokens > 0 {
		data["context_peak"] = node.ContextPeakTokens
	}
	if node.ContextCostUSD > 0 {
		data["context_cost"] = fmt.Sprintf("%.4f", node.ContextCostUSD)
	}

	// Edges
	data["has_edges"] = len(node.Edges) > 0
	if len(node.Edges) > 0 {
		data["edge_groups"] = prepareEdgeGroups(node)
	}

	// Steps
	data["has_steps"] = len(node.Steps) > 0
	if len(node.Steps) > 0 {
		data["steps"] = prepareSteps(node.Steps)
	}

	// Properties
	data["has_properties"] = len(node.Properties) > 0
	if len(node.Properties) > 0 {
		data["properties"] = prepareProperties(node.Properties)
	}

	// Content
	data["has_content"] = node.Content != ""
	if node.Content != "" {
		data["content"] = node.Content
	}

	return data
}

// prepareEdgeGroups converts edges into template-friendly grouped structure.
func prepareEdgeGroups(node *models.Node) []map[string]any {
	var groups []map[string]any
	for relType, edges := range node.Edges {
		edgeList := make([]map[string]any, 0, len(edges))
		for _, e := range edges {
			entry := map[string]any{
				"href":         edgeHref(e),
				"relationship": string(e.Relationship),
				"title":        edgeTitle(e),
			}
			if !e.Since.IsZero() {
				entry["since"] = formatTime(e.Since)
			}
			edgeList = append(edgeList, entry)
		}
		groups = append(groups, map[string]any{
			"relationship":         relType,
			"relationship_display": relationshipDisplay(relType),
			"edges":                edgeList,
		})
	}
	return groups
}

// prepareSteps converts steps into template-friendly maps.
func prepareSteps(steps []models.Step) []map[string]any {
	result := make([]map[string]any, 0, len(steps))
	for _, s := range steps {
		entry := map[string]any{
			"completed":   fmt.Sprintf("%t", s.Completed),
			"description": s.Description,
		}
		if s.Completed {
			entry["icon"] = "\u2705" // check mark
		} else {
			entry["icon"] = "\u23F3" // hourglass
		}
		if s.StepID != "" {
			entry["step_id"] = s.StepID
		}
		if s.Agent != "" {
			entry["agent"] = s.Agent
		}
		if len(s.DependsOn) > 0 {
			entry["depends_on"] = strings.Join(s.DependsOn, ",")
		}
		result = append(result, entry)
	}
	return result
}

// prepareProperties converts a properties map to template-friendly list.
func prepareProperties(props map[string]any) []map[string]any {
	result := make([]map[string]any, 0, len(props))
	for key, val := range props {
		result = append(result, map[string]any{
			"key":           key,
			"display_key":   titleCase(strings.ReplaceAll(key, "_", " ")),
			"value":         fmt.Sprintf("%v", val),
			"display_value": fmt.Sprintf("%v", val),
		})
	}
	return result
}

// prepareSessionData converts a Session into a map for Mustache rendering.
func prepareSessionData(sess *models.Session) map[string]any {
	title := "Session " + sess.SessionID
	data := map[string]any{
		"id":              sess.SessionID,
		"title":           title,
		"status":          sess.Status,
		"status_display":  titleCase(sess.Status),
		"agent":           sess.AgentAssigned,
		"started_at":      formatTime(sess.CreatedAt),
		"last_activity":   formatTime(sess.CreatedAt), // best available
		"event_count":     sess.TotalEvents,
		"is_subagent":     fmt.Sprintf("%t", sess.IsSubagent),
		"stylesheet_path": "../styles.css",
	}

	if sess.StartCommit != "" {
		data["start_commit"] = sess.StartCommit
	}
	if sess.CompletedAt != nil {
		data["ended_at"] = formatTime(*sess.CompletedAt)
	}
	if sess.ParentSessionID != "" {
		data["parent_session"] = sess.ParentSessionID
	}
	if sess.ParentEventID != "" {
		data["parent_activity"] = sess.ParentEventID
	}

	// Edges from worked-on features
	var edgeGroups []map[string]any
	workedOn := parseJSONStringSlice(sess.FeaturesWorkedOn)
	if len(workedOn) > 0 {
		edgeList := make([]map[string]any, 0, len(workedOn))
		for _, fid := range workedOn {
			edgeList = append(edgeList, map[string]any{
				"href":         "../features/" + fid + ".html",
				"relationship": "worked-on",
				"title":        fid,
			})
		}
		edgeGroups = append(edgeGroups, map[string]any{
			"relationship":         "worked-on",
			"relationship_display": "Worked On",
			"edges":                edgeList,
		})
	}
	if sess.ContinuedFrom != "" {
		edgeGroups = append(edgeGroups, map[string]any{
			"relationship":         "continued-from",
			"relationship_display": "Continued From",
			"edges": []map[string]any{{
				"href":         sess.ContinuedFrom + ".html",
				"relationship": "continued-from",
				"title":        sess.ContinuedFrom,
			}},
		})
	}
	data["has_edges"] = len(edgeGroups) > 0
	data["edge_groups"] = edgeGroups

	// Handoff
	hasHandoff := sess.HandoffNotes != "" || sess.RecommendedNext != ""
	blockers := parseJSONStringSlice(sess.Blockers)
	if len(blockers) > 0 {
		hasHandoff = true
	}
	data["has_handoff"] = hasHandoff
	if sess.HandoffNotes != "" {
		data["handoff_notes"] = sess.HandoffNotes
	}
	if sess.RecommendedNext != "" {
		data["recommended_next"] = sess.RecommendedNext
	}
	data["has_blockers"] = len(blockers) > 0
	data["blockers"] = blockers

	return data
}
