package sdk

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/shakestzd/htmlgraph/internal/models"
)

// WriteNodeHTML serialises a Node to the canonical HtmlGraph HTML format and
// writes it to the collection directory.  The output MUST be parseable by
// htmlparse.ParseFile to ensure round-trip fidelity.
//
// Returns the absolute path of the written file.
func WriteNodeHTML(dir string, node *models.Node) (string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", fmt.Errorf("create dir %s: %w", dir, err)
	}

	path := filepath.Join(dir, node.ID+".html")
	html := renderNodeHTML(node)

	if err := os.WriteFile(path, []byte(html), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", path, err)
	}
	return path, nil
}

// renderNodeHTML produces the full HTML document for a node.
// Mirrors Python's Node.to_html() output.
func renderNodeHTML(n *models.Node) string {
	var b strings.Builder

	// Header boilerplate
	b.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="htmlgraph-version" content="1.0">
    <title>`)
	b.WriteString(escapeHTML(n.Title))
	b.WriteString(`</title>
    <link rel="stylesheet" href="../styles.css">
</head>
<body>
    <article id="`)
	b.WriteString(n.ID)
	b.WriteString(`"
             data-type="`)
	b.WriteString(n.Type)
	b.WriteString(`"
             data-status="`)
	b.WriteString(string(n.Status))
	b.WriteString(`"
             data-priority="`)
	b.WriteString(string(n.Priority))
	b.WriteString(`"
             data-created="`)
	b.WriteString(fmtTime(n.CreatedAt))
	b.WriteString(`"
             data-updated="`)
	b.WriteString(fmtTime(n.UpdatedAt))
	b.WriteString(`"`)

	if n.AgentAssigned != "" {
		b.WriteString(` data-agent-assigned="`)
		b.WriteString(n.AgentAssigned)
		b.WriteString(`"`)
	}
	if n.TrackID != "" {
		b.WriteString(` data-track-id="`)
		b.WriteString(n.TrackID)
		b.WriteString(`"`)
	}
	if n.SpikeSubtype != "" {
		b.WriteString(` data-spike-subtype="`)
		b.WriteString(n.SpikeSubtype)
		b.WriteString(`"`)
	}
	if n.SessionID != "" {
		b.WriteString(` data-session-id="`)
		b.WriteString(n.SessionID)
		b.WriteString(`"`)
	}
	if n.AutoGenerated {
		b.WriteString(` data-auto-generated="true"`)
	}
	if n.FromFeatureID != "" {
		b.WriteString(` data-from-feature-id="`)
		b.WriteString(n.FromFeatureID)
		b.WriteString(`"`)
	}
	if n.ToFeatureID != "" {
		b.WriteString(` data-to-feature-id="`)
		b.WriteString(n.ToFeatureID)
		b.WriteString(`"`)
	}
	if n.ModelName != "" {
		b.WriteString(` data-model-name="`)
		b.WriteString(n.ModelName)
		b.WriteString(`"`)
	}
	if n.ClaimedBySession != "" {
		b.WriteString(` data-claimed-by-session="`)
		b.WriteString(n.ClaimedBySession)
		b.WriteString(`"`)
	}

	b.WriteString(">\n\n")

	// Header section
	statusLabel := strings.ReplaceAll(string(n.Status), "-", " ")
	statusLabel = titleCase(statusLabel)
	priorityLabel := titleCase(string(n.Priority))

	b.WriteString("        <header>\n")
	b.WriteString("            <h1>")
	b.WriteString(escapeHTML(n.Title))
	b.WriteString("</h1>\n")
	b.WriteString("            <div class=\"metadata\">\n")
	b.WriteString("                <span class=\"badge status-")
	b.WriteString(string(n.Status))
	b.WriteString("\">")
	b.WriteString(statusLabel)
	b.WriteString("</span>\n")
	b.WriteString("                <span class=\"badge priority-")
	b.WriteString(string(n.Priority))
	b.WriteString("\">")
	b.WriteString(priorityLabel)
	b.WriteString(" Priority</span>\n")
	b.WriteString("            </div>\n")
	b.WriteString("        </header>\n")

	// Edges
	if len(n.Edges) > 0 {
		b.WriteString("\n        <nav data-graph-edges>")
		for relType, edges := range n.Edges {
			if len(edges) == 0 {
				continue
			}
			b.WriteString("\n            <section data-edge-type=\"")
			b.WriteString(relType)
			b.WriteString("\">\n")
			b.WriteString("                <h3>")
			b.WriteString(titleCase(strings.ReplaceAll(relType, "_", " ")))
			b.WriteString(":</h3>\n")
			b.WriteString("                <ul>\n")
			for _, edge := range edges {
				b.WriteString("                    <li><a href=\"")
				b.WriteString(edge.TargetID)
				b.WriteString(".html\" data-relationship=\"")
				b.WriteString(string(edge.Relationship))
				b.WriteString("\"")
				if !edge.Since.IsZero() {
					b.WriteString(" data-since=\"")
					b.WriteString(fmtTime(edge.Since))
					b.WriteString("\"")
				}
				b.WriteString(">")
				label := edge.Title
				if label == "" {
					label = edge.TargetID
				}
				b.WriteString(escapeHTML(label))
				b.WriteString("</a></li>\n")
			}
			b.WriteString("                </ul>\n")
			b.WriteString("            </section>")
		}
		b.WriteString("\n        </nav>\n")
	}

	// Steps
	if len(n.Steps) > 0 {
		b.WriteString("\n        <section data-steps>\n")
		b.WriteString("            <h3>Implementation Steps</h3>\n")
		b.WriteString("            <ol>\n")
		for _, step := range n.Steps {
			emoji := "\u23F3" // hourglass
			if step.Completed {
				emoji = "\u2705" // checkmark
			}
			b.WriteString("                <li data-completed=\"")
			if step.Completed {
				b.WriteString("true")
			} else {
				b.WriteString("false")
			}
			b.WriteString("\"")
			if step.Agent != "" {
				b.WriteString(" data-agent=\"")
				b.WriteString(step.Agent)
				b.WriteString("\"")
			}
			if step.StepID != "" {
				b.WriteString(" data-step-id=\"")
				b.WriteString(step.StepID)
				b.WriteString("\"")
			}
			if len(step.DependsOn) > 0 {
				b.WriteString(" data-depends-on=\"")
				b.WriteString(strings.Join(step.DependsOn, ","))
				b.WriteString("\"")
			}
			b.WriteString(">")
			b.WriteString(emoji)
			b.WriteString(" ")
			b.WriteString(escapeHTML(step.Description))
			b.WriteString("</li>\n")
		}
		b.WriteString("            </ol>\n")
		b.WriteString("        </section>\n")
	}

	// Content
	if n.Content != "" {
		b.WriteString("\n        <section data-content>\n")
		b.WriteString("            <h3>Description</h3>\n")
		b.WriteString("            ")
		b.WriteString(n.Content)
		b.WriteString("\n        </section>\n")
	}

	// Close
	b.WriteString("    </article>\n</body>\n</html>\n")

	return b.String()
}

// fmtTime formats a time.Time in Python-compatible ISO-8601.
func fmtTime(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.Format("2006-01-02T15:04:05.999999")
}

// escapeHTML performs minimal HTML entity escaping.
func escapeHTML(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	s = strings.ReplaceAll(s, "\"", "&quot;")
	return s
}

// titleCase capitalises the first letter of each word.
func titleCase(s string) string {
	words := strings.Fields(s)
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}
