package sdk

import (
	"strings"
	"time"

	"github.com/shakestzd/htmlgraph/internal/models"
)

// Predicate is a composable filter function over graph nodes.
// Predicates can be combined with And, Or, and Not to build
// expressive queries without a custom DSL parser.
type Predicate func(*models.Node) bool

// --- Leaf predicates --------------------------------------------------------

// StatusIs matches nodes whose status equals the given value.
func StatusIs(status string) Predicate {
	return func(n *models.Node) bool {
		return string(n.Status) == status
	}
}

// PriorityIs matches nodes whose priority equals the given value.
func PriorityIs(p string) Predicate {
	return func(n *models.Node) bool {
		return string(n.Priority) == p
	}
}

// TrackIs matches nodes linked to the given track ID.
func TrackIs(id string) Predicate {
	return func(n *models.Node) bool {
		return n.TrackID == id
	}
}

// AgentIs matches nodes assigned to the given agent.
func AgentIs(agent string) Predicate {
	return func(n *models.Node) bool {
		return n.AgentAssigned == agent
	}
}

// TypeIs matches nodes of the given type (e.g. "feature", "bug", "spike").
func TypeIs(t string) Predicate {
	return func(n *models.Node) bool {
		return n.Type == t
	}
}

// TitleContains matches nodes whose title contains sub (case-insensitive).
func TitleContains(sub string) Predicate {
	lower := strings.ToLower(sub)
	return func(n *models.Node) bool {
		return strings.Contains(strings.ToLower(n.Title), lower)
	}
}

// ContentContains matches nodes whose content contains sub (case-insensitive).
func ContentContains(sub string) Predicate {
	lower := strings.ToLower(sub)
	return func(n *models.Node) bool {
		return strings.Contains(strings.ToLower(n.Content), lower)
	}
}

// CreatedAfter matches nodes created strictly after the given time.
func CreatedAfter(t time.Time) Predicate {
	return func(n *models.Node) bool {
		return n.CreatedAt.After(t)
	}
}

// CreatedBefore matches nodes created strictly before the given time.
func CreatedBefore(t time.Time) Predicate {
	return func(n *models.Node) bool {
		return n.CreatedAt.Before(t)
	}
}

// UpdatedAfter matches nodes updated strictly after the given time.
func UpdatedAfter(t time.Time) Predicate {
	return func(n *models.Node) bool {
		return n.UpdatedAt.After(t)
	}
}

// HasSteps matches nodes that have at least one step defined.
func HasSteps() Predicate {
	return func(n *models.Node) bool {
		return len(n.Steps) > 0
	}
}

// IsAutoGenerated matches nodes flagged as auto-generated.
func IsAutoGenerated() Predicate {
	return func(n *models.Node) bool {
		return n.AutoGenerated
	}
}

// CompletionAbove matches nodes whose completion percentage exceeds pct.
func CompletionAbove(pct int) Predicate {
	return func(n *models.Node) bool {
		return n.CompletionPercentage() > pct
	}
}

// CompletionBelow matches nodes whose completion percentage is below pct.
func CompletionBelow(pct int) Predicate {
	return func(n *models.Node) bool {
		return n.CompletionPercentage() < pct
	}
}

// --- Combinators ------------------------------------------------------------

// And returns a predicate that is true when all given predicates are true.
func And(preds ...Predicate) Predicate {
	return func(n *models.Node) bool {
		for _, p := range preds {
			if !p(n) {
				return false
			}
		}
		return true
	}
}

// Or returns a predicate that is true when any given predicate is true.
func Or(preds ...Predicate) Predicate {
	return func(n *models.Node) bool {
		for _, p := range preds {
			if p(n) {
				return true
			}
		}
		return false
	}
}

// Not returns a predicate that negates the given predicate.
func Not(p Predicate) Predicate {
	return func(n *models.Node) bool {
		return !p(n)
	}
}
