package sdk_test

import (
	"testing"
	"time"

	"github.com/shakestzd/htmlgraph/internal/models"
	"github.com/shakestzd/htmlgraph/pkg/sdk"
)

// ---------------------------------------------------------------------------
// Predicate tests
// ---------------------------------------------------------------------------

func TestStatusIs(t *testing.T) {
	n := &models.Node{Status: models.StatusInProgress}
	if !sdk.StatusIs("in-progress")(n) {
		t.Error("expected match for in-progress")
	}
	if sdk.StatusIs("done")(n) {
		t.Error("should not match done")
	}
}

func TestPriorityIs(t *testing.T) {
	n := &models.Node{Priority: models.PriorityHigh}
	if !sdk.PriorityIs("high")(n) {
		t.Error("expected match for high")
	}
	if sdk.PriorityIs("low")(n) {
		t.Error("should not match low")
	}
}

func TestTrackIs(t *testing.T) {
	n := &models.Node{TrackID: "trk-abc"}
	if !sdk.TrackIs("trk-abc")(n) {
		t.Error("expected match")
	}
	if sdk.TrackIs("trk-other")(n) {
		t.Error("should not match")
	}
}

func TestAgentIs(t *testing.T) {
	n := &models.Node{AgentAssigned: "opus"}
	if !sdk.AgentIs("opus")(n) {
		t.Error("expected match")
	}
	if sdk.AgentIs("haiku")(n) {
		t.Error("should not match")
	}
}

func TestTypeIs(t *testing.T) {
	n := &models.Node{Type: "feature"}
	if !sdk.TypeIs("feature")(n) {
		t.Error("expected match")
	}
	if sdk.TypeIs("bug")(n) {
		t.Error("should not match")
	}
}

func TestTitleContains(t *testing.T) {
	n := &models.Node{Title: "User Authentication Flow"}
	if !sdk.TitleContains("auth")(n) {
		t.Error("expected case-insensitive match")
	}
	if sdk.TitleContains("payment")(n) {
		t.Error("should not match")
	}
}

func TestContentContains(t *testing.T) {
	n := &models.Node{Content: "<p>Implements OAuth2 flow</p>"}
	if !sdk.ContentContains("oauth2")(n) {
		t.Error("expected case-insensitive match")
	}
	if sdk.ContentContains("saml")(n) {
		t.Error("should not match")
	}
}

func TestCreatedAfterBefore(t *testing.T) {
	ref := time.Date(2026, 1, 15, 0, 0, 0, 0, time.UTC)
	n := &models.Node{CreatedAt: time.Date(2026, 1, 20, 0, 0, 0, 0, time.UTC)}

	if !sdk.CreatedAfter(ref)(n) {
		t.Error("expected CreatedAfter match")
	}
	if sdk.CreatedBefore(ref)(n) {
		t.Error("should not match CreatedBefore")
	}
}

func TestUpdatedAfter(t *testing.T) {
	ref := time.Date(2026, 3, 1, 0, 0, 0, 0, time.UTC)
	n := &models.Node{UpdatedAt: time.Date(2026, 3, 15, 0, 0, 0, 0, time.UTC)}
	if !sdk.UpdatedAfter(ref)(n) {
		t.Error("expected match")
	}
}

func TestHasSteps(t *testing.T) {
	with := &models.Node{Steps: []models.Step{{Description: "step 1"}}}
	without := &models.Node{}
	if !sdk.HasSteps()(with) {
		t.Error("expected match with steps")
	}
	if sdk.HasSteps()(without) {
		t.Error("should not match without steps")
	}
}

func TestIsAutoGenerated(t *testing.T) {
	auto := &models.Node{AutoGenerated: true}
	manual := &models.Node{AutoGenerated: false}
	if !sdk.IsAutoGenerated()(auto) {
		t.Error("expected match")
	}
	if sdk.IsAutoGenerated()(manual) {
		t.Error("should not match")
	}
}

func TestCompletionAboveBelow(t *testing.T) {
	n := &models.Node{
		Status: models.StatusInProgress,
		Steps: []models.Step{
			{Description: "a", Completed: true},
			{Description: "b", Completed: false},
		},
	}
	// 50% completion
	if !sdk.CompletionAbove(40)(n) {
		t.Error("expected above 40")
	}
	if sdk.CompletionAbove(60)(n) {
		t.Error("should not be above 60")
	}
	if !sdk.CompletionBelow(60)(n) {
		t.Error("expected below 60")
	}
	if sdk.CompletionBelow(40)(n) {
		t.Error("should not be below 40")
	}
}

// ---------------------------------------------------------------------------
// Combinator tests
// ---------------------------------------------------------------------------

func TestAnd(t *testing.T) {
	n := &models.Node{
		Status:   models.StatusInProgress,
		Priority: models.PriorityHigh,
	}
	pred := sdk.And(sdk.StatusIs("in-progress"), sdk.PriorityIs("high"))
	if !pred(n) {
		t.Error("expected And to match")
	}

	pred2 := sdk.And(sdk.StatusIs("in-progress"), sdk.PriorityIs("low"))
	if pred2(n) {
		t.Error("And should not match when one predicate fails")
	}
}

func TestOr(t *testing.T) {
	n := &models.Node{Status: models.StatusTodo}
	pred := sdk.Or(sdk.StatusIs("todo"), sdk.StatusIs("blocked"))
	if !pred(n) {
		t.Error("expected Or to match")
	}

	pred2 := sdk.Or(sdk.StatusIs("done"), sdk.StatusIs("blocked"))
	if pred2(n) {
		t.Error("Or should not match when no predicates match")
	}
}

func TestNot(t *testing.T) {
	n := &models.Node{Status: models.StatusDone}
	pred := sdk.Not(sdk.StatusIs("done"))
	if pred(n) {
		t.Error("Not(done) should not match a done node")
	}
	pred2 := sdk.Not(sdk.StatusIs("todo"))
	if !pred2(n) {
		t.Error("Not(todo) should match a done node")
	}
}

// ---------------------------------------------------------------------------
// Query builder integration tests (with real HTML files on disk)
// ---------------------------------------------------------------------------

func TestQueryExecuteWithPredicates(t *testing.T) {
	s := newTestSDK(t)

	// Create test features with different statuses/priorities.
	_, err := s.Features.Create("Alpha Feature",
		sdk.FeatWithPriority("high"), sdk.FeatWithStatus("in-progress"))
	if err != nil {
		t.Fatalf("create Alpha: %v", err)
	}
	_, err = s.Features.Create("Beta Feature",
		sdk.FeatWithPriority("low"), sdk.FeatWithStatus("todo"))
	if err != nil {
		t.Fatalf("create Beta: %v", err)
	}
	_, err = s.Features.Create("Gamma Feature",
		sdk.FeatWithPriority("high"), sdk.FeatWithStatus("todo"))
	if err != nil {
		t.Fatalf("create Gamma: %v", err)
	}

	// Find high-priority features.
	nodes, err := s.Find("features").
		Where(sdk.PriorityIs("high")).
		Execute()
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if len(nodes) != 2 {
		t.Fatalf("expected 2 high-priority, got %d", len(nodes))
	}

	// Find todo + high.
	nodes, err = s.Find("features").
		Where(sdk.StatusIs("todo")).
		Where(sdk.PriorityIs("high")).
		Execute()
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if len(nodes) != 1 {
		t.Fatalf("expected 1 todo+high, got %d", len(nodes))
	}
	if nodes[0].Title != "Gamma Feature" {
		t.Errorf("expected Gamma, got %q", nodes[0].Title)
	}
}

func TestQueryOrderBy(t *testing.T) {
	s := newTestSDK(t)

	_, _ = s.Features.Create("Charlie", sdk.FeatWithPriority("low"))
	_, _ = s.Features.Create("Alpha", sdk.FeatWithPriority("high"))
	_, _ = s.Features.Create("Bravo", sdk.FeatWithPriority("medium"))

	// Sort by title ascending.
	nodes, err := s.Find("features").
		OrderBy("title", sdk.Asc).
		Execute()
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if len(nodes) < 3 {
		t.Fatalf("expected 3 nodes, got %d", len(nodes))
	}
	if nodes[0].Title != "Alpha" {
		t.Errorf("first should be Alpha, got %q", nodes[0].Title)
	}
	if nodes[2].Title != "Charlie" {
		t.Errorf("last should be Charlie, got %q", nodes[2].Title)
	}

	// Sort by priority descending (critical > high > medium > low).
	nodes, err = s.Find("features").
		OrderBy("priority", sdk.Desc).
		Execute()
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if string(nodes[0].Priority) != "high" {
		t.Errorf("first should be high priority, got %q", nodes[0].Priority)
	}
	if string(nodes[len(nodes)-1].Priority) != "low" {
		t.Errorf("last should be low priority, got %q", nodes[len(nodes)-1].Priority)
	}
}

func TestQueryLimit(t *testing.T) {
	s := newTestSDK(t)

	for i := 0; i < 5; i++ {
		_, _ = s.Features.Create("Feature "+string(rune('A'+i)))
	}

	nodes, err := s.Find("features").Limit(3).Execute()
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if len(nodes) != 3 {
		t.Errorf("expected 3 nodes, got %d", len(nodes))
	}
}

func TestQueryFirst(t *testing.T) {
	s := newTestSDK(t)

	_, _ = s.Features.Create("Only One")

	node, err := s.Find("features").First()
	if err != nil {
		t.Fatalf("First: %v", err)
	}
	if node.Title != "Only One" {
		t.Errorf("expected 'Only One', got %q", node.Title)
	}
}

func TestQueryFirstNoResults(t *testing.T) {
	s := newTestSDK(t)

	_, err := s.Find("features").
		Where(sdk.StatusIs("blocked")).
		First()
	if err == nil {
		t.Error("expected error for empty result set")
	}
}

func TestQueryCount(t *testing.T) {
	s := newTestSDK(t)

	_, _ = s.Features.Create("A", sdk.FeatWithStatus("todo"))
	_, _ = s.Features.Create("B", sdk.FeatWithStatus("in-progress"))
	_, _ = s.Features.Create("C", sdk.FeatWithStatus("todo"))

	count, err := s.Find("features").
		Where(sdk.StatusIs("todo")).
		Count()
	if err != nil {
		t.Fatalf("Count: %v", err)
	}
	if count != 2 {
		t.Errorf("expected 2, got %d", count)
	}
}

func TestQueryFindAll(t *testing.T) {
	s := newTestSDK(t)

	_, _ = s.Features.Create("Feature X")
	_, _ = s.Bugs.Create("Bug Y")
	_, _ = s.Spikes.Create("Spike Z")

	nodes, err := s.FindAll().Execute()
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if len(nodes) != 3 {
		t.Errorf("expected 3 across all collections, got %d", len(nodes))
	}
}

func TestQueryFindAllWithTypeFilter(t *testing.T) {
	s := newTestSDK(t)

	_, _ = s.Features.Create("Feature X")
	_, _ = s.Bugs.Create("Bug Y")
	_, _ = s.Spikes.Create("Spike Z")

	nodes, err := s.FindAll().
		Where(sdk.TypeIs("bug")).
		Execute()
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if len(nodes) != 1 {
		t.Errorf("expected 1 bug, got %d", len(nodes))
	}
	if nodes[0].Type != "bug" {
		t.Errorf("expected bug type, got %q", nodes[0].Type)
	}
}

func TestQueryUnknownCollection(t *testing.T) {
	s := newTestSDK(t)

	_, err := s.Find("nonexistent").Execute()
	if err == nil {
		t.Error("expected error for unknown collection")
	}
}

func TestQueryTitleContainsFilter(t *testing.T) {
	s := newTestSDK(t)

	_, _ = s.Features.Create("User Authentication")
	_, _ = s.Features.Create("Payment Processing")
	_, _ = s.Features.Create("Auth Token Refresh")

	nodes, err := s.Find("features").
		Where(sdk.TitleContains("auth")).
		Execute()
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if len(nodes) != 2 {
		t.Errorf("expected 2 matches for 'auth', got %d", len(nodes))
	}
}

func TestQueryCombinedPredicatesWithOr(t *testing.T) {
	s := newTestSDK(t)

	_, _ = s.Features.Create("A", sdk.FeatWithStatus("todo"))
	_, _ = s.Features.Create("B", sdk.FeatWithStatus("blocked"))
	_, _ = s.Features.Create("C", sdk.FeatWithStatus("done"))

	// Find items that are either todo or blocked.
	nodes, err := s.Find("features").
		Where(sdk.Or(sdk.StatusIs("todo"), sdk.StatusIs("blocked"))).
		Execute()
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if len(nodes) != 2 {
		t.Errorf("expected 2 (todo or blocked), got %d", len(nodes))
	}
}

func TestQueryNotPredicate(t *testing.T) {
	s := newTestSDK(t)

	_, _ = s.Features.Create("A", sdk.FeatWithStatus("done"))
	_, _ = s.Features.Create("B", sdk.FeatWithStatus("todo"))
	_, _ = s.Features.Create("C", sdk.FeatWithStatus("in-progress"))

	// Find items that are NOT done.
	nodes, err := s.Find("features").
		Where(sdk.Not(sdk.StatusIs("done"))).
		Execute()
	if err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if len(nodes) != 2 {
		t.Errorf("expected 2 not-done, got %d", len(nodes))
	}
}
